feat: addFriend by userId
KATITB2023/social pull request #3
Opened 2023-07-20 02:39 UTC by putrafurqan

2023-07-20 18:17 UTC, chaerla commented on src/server/api/routers/friend.ts
> +            await ctx.prisma.friendship.updateMany({
- Fitur bisa bisa pakai .update() saja, tidak perlu updateMany, where id = friendship.id

2023-07-20 18:18 UTC, chaerla commented on src/server/api/routers/friend.ts
> +                },
- `in` itu dipakai kalau yang mau dicocokin berupa array. Kalau hanya satu data saja, pakai where saja. mis: userInitiatorId: userId

2023-07-20 18:19 UTC, chaerla commented on src/server/api/routers/friend.ts
> +      }
return code 400 aja, BAD REQUEST

2023-07-20 18:20 UTC, chaerla requested changes, later dismissed
Overall udah oke dan codenya fungsional untuk different cases. Bisa diimprove, untuk improvementnya udah dicomment di commitnya. Good job!

2023-07-20 18:21 UTC, chaerla commented
@akbarmridho boleh direview further ya bar

2023-07-21 01:01 UTC, chaerla commented
kalau bisa keynya jangan ditaruh di folder repo nya yaa.

2023-07-21 01:34 UTC, akbarmridho commented
generate ulang key yang kamu pake buat github, udah gak aman

2023-07-21 01:42 UTC, akbarmridho approved these changes
secara umum udah hampir benar. masih ada salah di query terima frienship request, tapi udah aku benerin

2023-07-21 01:42 UTC, akbarmridho commented on src/server/api/routers/friend.ts
> +            await ctx.prisma.friendship.updateMany({
query masih salah, kalo gini bakal update banyak permintaan pertemanan

2023-07-21 01:43 UTC, akbarmridho approved these changes

2023-07-21 01:45 UTC, merged