feat: integrasi login page
KATITB2023/social pull request #43
Opened 2023-08-05 02:23 UTC by slntkllr01

## Story/Task

https://trello.com/c/q92eD33H/72-fe4-integrasi-login-page

## Summary

add 3 new pages :
1. login-page.tsx
2. login-background.tsx
3. forgot-password.tsx

selain itu, saya juga menambahkan beberapa elemen gambar untuk keperluan "login-background.tsx"

## Screenshot

![image](https://github.com/KATITB2023/social/assets/114353406/6fe0832c-18a6-478f-afa5-e08bd5f298b0)
![image](https://github.com/KATITB2023/social/assets/114353406/2e600530-5ab0-412f-a2e8-47982935db5d)
![image](https://github.com/KATITB2023/social/assets/114353406/1aff3bb3-5973-4f01-8ea7-74f4686f73d2)
![image](https://github.com/KATITB2023/social/assets/114353406/ce48b565-a8c0-45a7-becc-1e78616e8090)

2023-08-05 02:49 UTC, pandora-1 requested changes
Button kirim dan login nya keliatannya agak transparan ya

2023-08-05 02:50 UTC, pandora-1 requested changes
Login Background dipindah ke dalam components aja, dibuatin folder login trus dimasukin di dalem situ

2023-08-05 02:51 UTC, pandora-1 requested changes
Nama file login-page.tsx diubah ke login.tsx agar routing nya jadi /login bukan /login-page

2023-08-05 03:00 UTC, slntkllr01 commented
> Button kirim dan login nya keliatannya agak transparan ya

Button tidak terlihat transparan jika user sudah menginput data dengan benar, kak

![image](https://github.com/KATITB2023/social/assets/114353406/af9bc3cd-9c50-42bc-8bad-a8e3773f9263)

2023-08-05 06:09 UTC, akbarmridho commented
hapus file zone identifier

2023-08-05 09:07 UTC, pandora-1 commented
> > Button kirim dan login nya keliatannya agak transparan ya
> 
> Button tidak terlihat transparan jika user sudah menginput data dengan benar, kak
> 
> ![image](https://user-images.githubusercontent.com/114353406/258559254-af9bc3cd-9c50-42bc-8bad-a8e3773f9263.png)

oke noted

2023-08-06 08:45 UTC, pandora-1 requested changes

2023-08-06 08:45 UTC, pandora-1 commented on src/pages/login-page.tsx
> +    role === UserRole.MENTOR
redirect nya langsung ke profile page aja, gak usah dicek dia mentor atau bukan yaa

2023-08-06 08:45 UTC, pandora-1 commented on src/pages/forgot-password.tsx
> +      });
habis handle success, diredirect ke login ajaa

2023-08-06 08:45 UTC, pandora-1 commented on src/pages/login.tsx
> +      ? void router.push('/attendance')
ini auto redirect ke /profile yaa, gak perlu cek user role

2023-08-06 08:45 UTC, pandora-1 commented on src/pages/login.tsx
> +  console.log(session);
ini dihapuss yaa

2023-08-06 08:45 UTC, pandora-1 commented on src/pages/forgot-password.tsx
> +                  background="#FFFC83"
untuk colornya diubah sesuai mengikuti design system yaa

2023-08-06 08:45 UTC, pandora-1 commented on src/pages/forgot-password.tsx
> +                  background="#FFFC83"
sama yang lain juga

2023-08-09 11:34 UTC, pandora-1 approved these changes

2023-08-09 11:34 UTC, merged