Feat: popup and loading screen
KATITB2023/social pull request #50
Opened 2023-08-07 11:44 UTC by akmalrmn

## Story/Task

git commit -m "feat: popup and loading screen"

## Summary

- Membuat popup component chat dan loading screen 
- _Fix previous bug_

## Screenshot

<img width="960" alt="image" src="https://github.com/KATITB2023/social/assets/118426250/d6de0538-cbfe-4ae8-a9bb-b02a816e0903">
<img width="960" alt="image" src="https://github.com/KATITB2023/social/assets/118426250/428299e7-d8a9-4dd7-9657-09ac50e00c7e">
<img width="960" alt="image" src="https://github.com/KATITB2023/social/assets/118426250/9f15d567-de1d-4ed7-be8b-3db223e4f0e7">

2023-08-07 12:14 UTC, akbarmridho commented
1. Jangan pakai npm dan push package-lock.json. Pakai yarn
2. Jangan hapus social.code-workspace
3. Ubah Popup_Chat jadi PopupChat
4. Jangan ubah tsconfig
5. Tidak perlu update package di package json, terlebih lagi mengubah versi dependency ke database
6. Reusability setiap component popup masih bisa ditingkatkan

2023-08-08 04:21 UTC, pandora-1 requested changes
Ini navbar emang diubah yaa?

2023-08-08 04:22 UTC, pandora-1 requested changes
Nama file component diubah juga ya, misal jadi BerhasilRequest.tsx

2023-08-08 04:23 UTC, pandora-1 requested changes
package.json, package-lock, yarn lock, tsconfig jangan ikut ke pull req yaa

2023-08-08 04:35 UTC, pandora-1 requested changes
Untuk yang style sama, bisa nih kamu buat jadi satu komponen sehingga dia bisa direuse. Misal, jika setiap popup ada 3 desain sama yang berbeda hanya konten nya saja, kamu bisa buat sebuah komponen yang nerima input teks content sehingga yang didisplay adalah parameter input teks dari user, sehingga hanya perlu buat 1 sajaa

2023-08-08 04:35 UTC, pandora-1 commented on src/components/PopupChat/berhasil-request.tsx
> +      background: "#1F1F2E",
Untuk warna mengikuti dari design system ya, contoh yellow.5 or yang lain

2023-08-08 04:35 UTC, pandora-1 commented on src/components/PopupChat/berhasil-request.tsx
> +      background: "#1F1F2E",
Berlaku juga untuk yang lain

2023-08-09 12:18 UTC, pandora-1 requested changes
Conflict nya diresolve dulu yaa

2023-08-09 17:46 UTC, pandora-1 approved these changes

2023-08-09 17:46 UTC, merged