Story/friends anonymous chats
KATITB2023/social pull request #51
Opened 2023-08-07 12:50 UTC by Gulilil

## Story/Task

_Link ke story/task di Trello_
https://trello.com/c/WpWHFRU3/76-fe-be8-chat-teman-dan-chat-anonim

## Summary

- Fixing Navbar making in fixed and sticky
- Friends Chat Page
- Anonymous Loading Page
- Anonymous Chat Page
- Anon Menu

## Screenshot

_Sediakan screenshot_: \
_Untuk FE di web dan mobile_ \
![messageImage_1691412360129](https://github.com/KATITB2023/social/assets/91795905/7658c0d0-f670-4031-8412-818366b4072c)
![messageImage_1691412380477](https://github.com/KATITB2023/social/assets/91795905/82b8dc04-c83b-4b07-91e3-8d5ee22ec618)

_Untuk BE screenrecord/gif/ss request dan response_

2023-08-08 23:51 UTC, pandora-1 requested changes
Konfliknya diresolve dulu yaa

2023-08-08 23:55 UTC, pandora-1 submitted a review, later dismissed

2023-08-08 23:55 UTC, pandora-1 commented on public/components/anon_chat_page/anon_menu.svg
File ini pakai png aja ya karena dia dalemnya png

2023-08-08 23:55 UTC, pandora-1 commented on src/components/chat/Header.tsx
> +              src="https://bit.ly/dan-abramov"
Ini masih data dummy kah?

2023-08-09 04:31 UTC, Gulilil commented on src/components/chat/Header.tsx
> +              src="https://bit.ly/dan-abramov"
oiyaa yang itu gambarnya kelupaan ku integrasi, sebentar kak

2023-08-09 04:31 UTC, Gulilil commented on public/components/anon_chat_page/anon_menu.svg
okee sebentar ku ganti kak

2023-08-09 09:57 UTC, akbarmridho approved these changes

2023-08-09 09:59 UTC, merged