Feat/integrate profile
KATITB2023/social pull request #53
Opened 2023-08-07 14:03 UTC by ganadipa

## Story/Task
https://trello.com/c/BTbl40ST

## Summary

integrate profile and also improve profile picture pop up

## Screenshot

![image](https://github.com/KATITB2023/social/assets/116704815/10401e24-5cc8-4148-9b7a-84a9b106d4d5)

2023-08-07 15:51 UTC, akbarmridho commented
kenapa cache control di tRPC dicomment?

2023-08-08 04:09 UTC, pandora-1 commented
> kenapa cache control di tRPC dicomment?

ini kemarin kinan usul gini, pas update profile, dia ngupdate data di page profile lama, perlu berapa detik gitu setelah edit, jadinya si kinan usul cache nya dicomment

2023-08-08 04:10 UTC, pandora-1 requested changes
Foto profile nya mungkin bisa dibuat bulat utuh yaa

2023-08-08 04:11 UTC, pandora-1 requested changes
Ini backgroundAndNavigationBar kepakai tidak ya? aku lihat dia tidak dipakai dimana-mana

2023-08-08 04:18 UTC, pandora-1 requested changes

2023-08-08 04:18 UTC, pandora-1 commented on src/components/profile/EditingProfile.tsx
> +      console.log(res);
Ini jangan lupa dihapus yaa console.log

2023-08-08 04:18 UTC, pandora-1 commented on src/components/profile/EditingProfile.tsx
> +    setIsUpdating(false);
Kelihatannya alurnya untuk UXnya better ika user gagal -> dia gak kembali ke mode non-updat, tapi masih di mode update sehingga user gak perlu input ulang, misal karena koneksi or something

2023-08-08 04:18 UTC, pandora-1 commented on src/components/profile/SelectPhotoImageProfile.tsx
> +      console.log(res);
Ini console log dihapus yaa

2023-08-08 04:18 UTC, pandora-1 commented on src/components/profile/SelectPhotoImageProfile.tsx
> +      console.error("File upload failed:", error);
Ini kalau error bisa ditambahin toast yaa

2023-08-08 04:18 UTC, pandora-1 commented on src/pages/profile.tsx
> +const defautProfile: SelfProfile = {
Ini kelihatannya tidak terpakai ya? Bisa dihapus yaa

2023-08-08 04:18 UTC, pandora-1 commented on src/pages/profile.tsx
> +          console.log("working...");
Ini dihapus ya console log nyaa

2023-08-08 04:19 UTC, pandora-1 requested changes
Untuk navbarnya pakai komponent yang sudah ada di components/navbar.tsx ya, gak perlu buat baruu

2023-08-08 04:19 UTC, pandora-1 requested changes
Jangan lupa juga pull req agar tidak conflict sama master

2023-08-09 02:36 UTC, ganadipa commented on src/components/profile/EditingProfile.tsx
> +    setIsUpdating(false);
done

2023-08-09 02:40 UTC, ganadipa commented on src/components/profile/SelectPhotoImageProfile.tsx
> +      console.log(res);
done

2023-08-09 12:12 UTC, pandora-1 approved these changes

2023-08-09 13:42 UTC, merged