feat: add integration on assignment page
KATITB2023/social pull request #59
Opened 2023-08-08 14:56 UTC by uliviaembun

## Story/Task

> [Integrasi Assignment Page](https://trello.com/c/y9ntlhVu)

## Summary

> Add integration on all of assignment page

## Screenshot

> 1. Tampilan Daily Quest
> ![Screenshot from 2023-08-08 21-38-02](https://github.com/KATITB2023/social/assets/121374094/7bd59786-06cd-4d31-b5b3-caece681222e)

> 2. Tampilan Side Quest
> ![Screenshot from 2023-08-08 21-38-07](https://github.com/KATITB2023/social/assets/121374094/f9d8dba4-66ab-4428-a3c6-86e89d2ae4f9)

> 3. Tampilan Belum Terkumpul
> ![Screenshot from 2023-08-08 21-20-14](https://github.com/KATITB2023/social/assets/121374094/5ae63655-11bb-437d-b38a-0840d4543f84)

> 4. Tampilan setelah pilih file
> ![Screenshot from 2023-08-08 21-20-47](https://github.com/KATITB2023/social/assets/121374094/3a79a884-c5d3-427f-8a4c-7bbfe04c0aba)

> 5. Tampilan Pop Up
> ![Screenshot from 2023-08-08 21-21-01](https://github.com/KATITB2023/social/assets/121374094/5b6eaa78-00ac-44cd-8193-bf64a00f088e)

> 6. Tampilan saat Tugas Berhasil Dikirim
> ![Screenshot from 2023-08-08 21-21-11](https://github.com/KATITB2023/social/assets/121374094/39e4b26b-9d76-45f3-b228-a476bf850392)

> 7. Tampilan saat Tugas Terkumpul
> ![Screenshot from 2023-08-08 21-21-22](https://github.com/KATITB2023/social/assets/121374094/b973abaf-a0e3-4f44-888e-d1ae1b131225)

> 8. Tampilan saat mau submit tanpa file
> ![Screenshot from 2023-08-08 21-20-28](https://github.com/KATITB2023/social/assets/121374094/ec1292ac-64cf-4c0d-8723-7b5c1a222921)

> 9. Tampilan Terlambat
> ![Screenshot from 2023-08-08 21-19-56](https://github.com/KATITB2023/social/assets/121374094/7e8d307a-5eed-4148-b189-f2904b4326e2)

2023-08-08 23:50 UTC, pandora-1 requested changes

2023-08-08 23:50 UTC, pandora-1 commented on src/components/assignment/SubmitPopUp.tsx
> +    console.log(sanitizedFileName)
Ini dihapus yaa

2023-08-08 23:50 UTC, pandora-1 commented on src/components/assignment/SubmitPopUp.tsx
> +      toast({
Perlu dilakukan pengecekan response dari result tuh 200 apa enggak, bisa jadi dia gagal gitu

2023-08-08 23:58 UTC, uliviaembun commented on src/components/assignment/SubmitPopUp.tsx
> +    console.log(sanitizedFileName)
console.lognya ya kak

2023-08-09 00:03 UTC, pandora-1 commented on src/components/assignment/SubmitPopUp.tsx
> +    console.log(sanitizedFileName)
iyaa

2023-08-09 04:20 UTC, pandora-1 approved these changes

2023-08-09 04:20 UTC, merged