Story/fe 3 integrate and create leaderboard pages
KATITB2023/social pull request #72
Opened 2023-08-10 05:39 UTC by Filbert88

## Story/Task

https://trello.com/c/nmfIfl0d/69-fe3-create-leaderboard-page
https://trello.com/c/WTRJ720i/70-fe4-integrasi-leaderboard-page

## Summary

create leaderboard page and integrate
revised Leaderboard card components
add some picts

## Screenshot

![image](https://github.com/KATITB2023/social/assets/92862064/1d72e57f-83e8-4471-a2a6-bffa1cbda4a2)
![image](https://github.com/KATITB2023/social/assets/92862064/07901c87-8c57-4db6-9f31-4d1aaf467a75)
![image](https://github.com/KATITB2023/social/assets/92862064/c1e5ae0a-30c4-47fa-837a-a64b30bf43c3)

2023-08-10 08:39 UTC, Gulilil requested changes
Secara gambaran besar codenya udah lgtm, tpi mungkin ada bbrp hal yang perlu diperhatiin:
1. Itu navbar masih di-comment, mungkin boleh di uncomment lagi aja. Buat paramsnya pake `Leaderboard` yaa. Jadi
     ` <Navbar currentPage = "Leaderboard" />` gitu.
2. Buat heightnya itu kan masih explicit height, 2000an px. Mungkin itu bisa dibikin sebagai maxH aja, jadi selama isinya ga sampai 2000an mungkin bisa dibatasin sesuai banyaknya data sampai maksimal heightnya 2000an px itu.
3. Buat lintnya jangan lupa di cek, run dulu aja `yarn lint`, abis itu resolve buat yang masih ada tulisan errornya.

2023-08-10 15:13 UTC, Filbert88 commented
> Secara gambaran besar codenya udah lgtm, tpi mungkin ada bbrp hal yang perlu diperhatiin:
> 
> 1. Itu navbar masih di-comment, mungkin boleh di uncomment lagi aja. Buat paramsnya pake `Leaderboard` yaa. Jadi
>    ` <Navbar currentPage = "Leaderboard" />` gitu.
> 2. Buat heightnya itu kan masih explicit height, 2000an px. Mungkin itu bisa dibikin sebagai maxH aja, jadi selama isinya ga sampai 2000an mungkin bisa dibatasin sesuai banyaknya data sampai maksimal heightnya 2000an px itu.
> 3. Buat lintnya jangan lupa di cek, run dulu aja `yarn lint`, abis itu resolve buat yang masih ada tulisan errornya.

done kak

2023-08-12 09:03 UTC, pandora-1 approved these changes

2023-08-12 09:04 UTC, Gulilil approved these changes

2023-08-12 09:05 UTC, merged